version: "3.8"

volumes:
  esdata01:
    driver: local

services:
  # oracle:
  #   build: ./docker/oracle/
  #   container_name: oracle
  #   #image: msdaf/oracle-sinprocesso:0.0.2
  #   environment:
  #     ORACLE_ENABLE_XDB: "true"
  #     ORACLE_ALLOW_REMOTE: "true"
  #   ports:
  #     - "49161:1521"
  #     - "8087:8080" #localhost:8087 APEX Oracle Admin View

 elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
   restart: unless-stopped
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
   ulimits:
     memlock:
       soft: -1
       hard: -1
   volumes:
     - esdata01:/usr/share/elasticsearch/data
     
 nifi:
   container_name: nifi
   image: apache/nifi:latest
   restart: unless-stopped
   volumes:
     - /tmp/nifi:/nifi
   ports:
     - "8080:8080"
   environment:
     - NIFI_WEB_HTTP_PORT=8080

 logstash:
   container_name: logstash
   image: docker.elastic.co/logstash/logstash:7.6.1
   ports:
     - "5000:5000/tcp"
     - "5000:5000/udp"
     - "9600:9600"
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
   depends_on:
     - elasticsearch

 kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.6.1
   restart: unless-stopped
   ports:
     - "5601:5601"
   environment:
     - SERVER_NAME=kibana.local
     - ELASTICSEARCH_URL=http://elasticsearch:9200
   depends_on:
     - elasticsearch
